# Default values for infocenter.

namespace: infocenter
infocenterVersion: 2023-09
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2023-09@sha256:ea500dcb3ee2ccdee140109e56c01745135262e3ed17088675a423bc9903e033"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
