#*******************************************************************************
# Copyright (c) 2023 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    infocenter.version: {{ .Values.infocenterVersion | quote }}
  namespace: {{ .Values.namespace | quote }}
  name: "{{ .Chart.Name }}-{{ .Values.infocenterVersion }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      infocenter.version: {{ .Values.infocenterVersion | quote }}
  #serviceName: "{{ .Chart.Name }}-{{ .Values.infocenterVersion}}"
  template:
    metadata:
      name: "{{ .Chart.Name }}-{{ .Values.infocenterVersion }}"
      labels:
        infocenter.version: {{ .Values.infocenterVersion | quote }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: speed
                operator: NotIn
                values:
                - fast
      terminationGracePeriodSeconds: 180
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.infocenterVersion }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /infocenter/startDockerInfoCenter.sh
        livenessProbe:
          httpGet:
            path: /help/index.jsp
            port: 8086
            scheme: HTTP
          initialDelaySeconds: 480
          periodSeconds: 60
          failureThreshold: 2
          timeoutSeconds: 90
        readinessProbe:
          httpGet:
            path: /help/index.jsp
            port: 8086
          periodSeconds: 60
          timeoutSeconds: 90
          initialDelaySeconds: 60
        ports:
        - containerPort: 8086
          protocol: TCP
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 2
            memory: 1.5Gi
        volumeMounts:
        - name: workspace
          mountPath: "/infocenter/workspace"
      volumes:
      - name: workspace
        emptyDir: {}
