#*******************************************************************************
# Copyright (c) 2023 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    infocenter.version: {{ .Values.infocenterVersion | quote }}
  namespace: {{ .Values.namespace | quote }}
  name: "{{ .Chart.Name }}-{{ .Values.infocenterVersion }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    protocol: "TCP"
    targetPort: {{ .Values.service.targetPort }}
  selector:
    infocenter.version: {{ .Values.infocenterVersion | quote }}
